M48
; DRILL file {KiCad 9.0.4} date 2026-03-31T17:48:20-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-31T17:48:20-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.400
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X55.0Y-79.415
X62.0Y-79.415
T2
X102.0Y-84.44
X102.0Y-117.44
X150.0Y-84.44
X150.0Y-117.44
M30
